data_file: "example.csv"
write_output: True
experiments:
    - name: "example_naive"
      model_class: TimeSeriesNaiveModel
      train_periods: 16
      model_kwargs:
      fit_kwargs:
    - name: "example_exponentialsmoothing"
      model_class: TimeSeriesExpSmoothingModel
      train_periods: 16
      model_kwargs:
          initialization_method : estimated
      fit_kwargs:
          smoothing_level : 0.5
    - name: "example_rollingaverage"
      model_class: TimeSeriesMean
      train_periods: 16
      model_kwargs:
      fit_kwargs: